# Generated by Django 6.0.3 on 2026-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('exam', 'Examen'), ('meeting', 'Réunion'), ('holiday', 'Vacances'), ('activity', 'Activité'), ('other', 'Autre')], max_length=20)),
                ('all_day', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(blank=True, related_name='events', to='school.class')),
            ],
        ),
    ]
