# Generated by Django 6.0.3 on 2026-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='XSCHOOL Management', max_length=200)),
                ('email', models.EmailField(default='contact@xschool.cm', max_length=254)),
                ('phone', models.CharField(default='+237 699 00 11 22', max_length=50)),
                ('address', models.TextField(default='Bastos, Yaoundé, Cameroun')),
                ('website', models.URLField(default='https://vanda-studio.tech')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
            ],
            options={
                'verbose_name': "Configuration de l'école",
                'verbose_name_plural': "Configuration de l'école",
            },
        ),
    ]
