# Generated by Django 6.0.3 on 2026-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='address',
            field=models.TextField(blank=True, default='Bastos, Yaoundé, Cameroun', null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='contact@xschool.cm', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='phone',
            field=models.CharField(blank=True, default='+237 699 00 11 22', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='website',
            field=models.URLField(blank=True, default='https://vanda-studio.tech', null=True),
        ),
    ]
