# Generated by Django 6.0.3 on 2026-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schoolconfiguration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enable_email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enable_sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='low_grade_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='payment_reminder_days',
            field=models.IntegerField(default=3),
        ),
    ]
