# Generated by Django 6.0.3 on 2026-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoolconfiguration_enable_email_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='currency_code',
            field=models.CharField(default='XAF', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='currency_symbol',
            field=models.CharField(default='FCFA', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enable_bank_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enable_cash_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enable_mobile_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='receipt_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
