# Generated by Django 6.0.3 on 2026-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_schoolconfiguration_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='min_password_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='require_strong_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='two_factor_enforcement',
            field=models.BooleanField(default=False),
        ),
    ]
