# Generated by Django 6.0.3 on 2026-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_schoolconfiguration_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='slogan',
            field=models.CharField(blank=True, default='EXCELLENCE & DISCIPLINE', max_length=200, null=True),
        ),
    ]
