# Generated by Django 6.0.3 on 2026-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_schoolconfiguration_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
