# Generated by Django 6.0.3 on 2026-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_repeating',
            field=models.BooleanField(default=False),
        ),
    ]
