# Generated by Django 6.0.3 on 2026-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_student_is_repeating'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('general', 'Enseignement Général'), ('technique', 'Enseignement Technique')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='exam_fee_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='tranche_1_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='tranche_2_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='tranche_3_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
