# Generated by Django 6.0.3 on 2026-04-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tuitiontemplate'),
        ('school', '0010_class_category_class_is_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tuition_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='finance.tuitiontemplate'),
        ),
    ]
