# Generated by Django 6.0.3 on 2026-04-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_class_tuition_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('level', 'school_year')},
        ),
    ]
