# Generated by Django 6.0.3 on 2026-04-21 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_class_options_alter_class_unique_together'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='period',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='student',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('level', 'school_year', 'establishment')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together={('year', 'establishment')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('matricule', 'establishment')},
        ),
    ]
