# Generated by Django 6.0.3 on 2026-04-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_class_unique_together_class_establishment_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='period',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
    ]
