# Generated by Django 6.0.3 on 2026-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_class_category_alter_class_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersanction',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
