# Generated by Django 6.0.3 on 2026-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_teachersanction_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='certificate_reference',
            field=models.CharField(blank=True, default='CERT/2026/', max_length=100, null=True),
        ),
    ]
