# Generated by Django 6.0.3 on 2026-04-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_schoolconfiguration_certificate_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='city',
            field=models.CharField(blank=True, default='Yaoundé', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='country',
            field=models.CharField(blank=True, default='Cameroun', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='director_title',
            field=models.CharField(blank=True, default="Le Chef d'Établissement", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='english_name',
            field=models.CharField(blank=True, default='XSCHOOL Institution', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='postal_code',
            field=models.CharField(blank=True, default='B.P. 1234', max_length=100, null=True),
        ),
    ]
