# Generated by Django 6.0.3 on 2026-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_schoolconfiguration_city_schoolconfiguration_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='article_text',
            field=models.TextField(blank=True, default="Décret N° 2024/001 du 01 Janvier 2024 portant création et ouverture de l'établissement.", null=True),
        ),
    ]
