# Generated by Django 6.0.3 on 2026-04-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('general', 'Enseignement Général'), ('technique', 'Enseignement Technique')], max_length=20)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tranche_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tranche_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tranche_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
