# Generated by Django 6.0.3 on 2026-04-21 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tuitiontemplate'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='trancheconfig',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AddField(
            model_name='tuitiontemplate',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.establishment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('receipt_number', 'establishment')},
        ),
    ]
