# Generated by Django 6.0.3 on 2026-04-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_establishment_and_more'),
        ('school', '0015_alter_class_category_alter_class_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.teacher'),
        ),
    ]
