# Generated by Django 6.0.3 on 2026-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_teacherpayment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpayment',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='total_sanctions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
