# Generated by Django 6.0.3 on 2026-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitiontemplate',
            name='category',
            field=models.CharField(choices=[('garderie', 'Garderie'), ('primaire', 'École Primaire'), ('general', 'Enseignement Général'), ('technique', 'Enseignement Technique'), ('formation', 'Centre de formation')], max_length=20),
        ),
    ]
